# Generated by Django 3.1.4 on 2020-12-07 02:36

import django.core.validators
from django.db import migrations, models
import movie.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actor', '0002_auto_20201207_0236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('director', models.CharField(blank=True, max_length=200, null=True, verbose_name='Director')),
                ('producer', models.CharField(blank=True, max_length=200, null=True, verbose_name='Producer')),
                ('release_year', models.IntegerField(default=movie.models.current_year, verbose_name='Release year')),
                ('rt_score', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Tomatometer score')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('actors', models.ManyToManyField(related_name='movies', to='actor.Actor')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'ordering': ('-created_at',),
            },
        ),
    ]
