# Generated by Django 3.1.4 on 2020-12-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="release_year",
            field=models.IntegerField(blank=True, null=True, verbose_name="Release year"),
        ),
    ]
