# Generated by Django 3.1.4 on 2020-12-08 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20201208_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rt_score',
            field=models.PositiveIntegerField(default=0, verbose_name='Tomatometer score'),
        ),
    ]
