# Generated by Django 3.1.4 on 2020-12-07 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Specie",
            fields=[
                ("id", models.UUIDField(db_index=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50, verbose_name="Name")),
                ("classification", models.CharField(max_length=50, verbose_name="Classification")),
            ],
            options={
                "verbose_name": "Specie",
                "verbose_name_plural": "Species",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Actor",
            fields=[
                ("id", models.UUIDField(db_index=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Fullname")),
                (
                    "gender",
                    models.CharField(
                        choices=[("unknown", "Unknown"), ("male", "Male"), ("female", "Female")],
                        default="unknown",
                        max_length=7,
                        verbose_name="Gender",
                    ),
                ),
                ("age", models.CharField(default="Unspecified", max_length=20, verbose_name="Age")),
                ("eye_color", models.CharField(default="Unspecified", max_length=20, verbose_name="Eye color")),
                ("hair_color", models.CharField(default="Unspecified", max_length=20, verbose_name="Hair color")),
                (
                    "specie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="actor.specie",
                        verbose_name="Specie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actor",
                "verbose_name_plural": "Actors",
                "ordering": ("name",),
            },
        ),
    ]
